FROM maven:3-jdk-11 as builder
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline

COPY src/ /build/src
RUN mvn clean package -DskipTests=true -Dspring.profiles.active=mysql

FROM openjdk:11-jdk-slim
EXPOSE 8080 8000
ENV JAVA_TOOL_OPTIONS "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000,quiet=y"
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Dspring.profiles.active=mysql", "-Dspring.datasource.url=jdbc:mysql://petclinic-db.default.svc.cluster.local/petclinic", "-jar", "/app.jar"]
COPY --from=builder /build/target/spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar /app.jar
